### ISSUE TITLE
Build failing with Meteor 1.3.x

### ISSUE THREAD

**Issue by Zodiase** [Zodiase/meteor-mdl#35]
``` Bash
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
* zodiase:mdl > Enabled with default settings. See documentation for customization options.
* zodiase:mdl > Enabled with default settings. See documentation for customization options.

/Users/xh/.meteor/packages/templating/.1.1.8.1eh0n9++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: true === "undefined"
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:160:12)
    at /tools/isobuild/import-scanner.js:146:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:119:11)
    at /tools/isobuild/compiler-plugin.js:788:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:759:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:680:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:671:18)
    at /tools/isobuild/bundler.js:2512:14
    at /tools/isobuild/bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/xh/.meteor/packages/meteor-tool/.1.3.1.1b2brxe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2601:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2493:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by ramijarrar** [comment]
Have you tried this with v1.3.1?

**Comment by seifip** [comment]
I get this error... both with 1.3.1 and 1.3.2.

```
C:\Users\Philip\AppData\Local\.meteor\packages\coffeescript\1.0.17-rc.4\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116C:\Users\Philip\Documents\GitHub\ll-app> meteor --settings settings.json
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  data: <Buffer 4d 44 6c 2e 73 65 74 74 69 6e 67 73 20 3d 20 4a 53 4f 4e 2e 70 61 72 73 65 28 64 65 63 6f 64 65 55 52 49 28 22 25 37 42 25 32 32 6a 73 4c 69 62 25 32 32 ...>,
  sourcePath: 'zodiase-mdl.json',
  servePath: '/client/lib/settings-file-checked.generated.js',
  hash: '7e71019794e668497fc7ce157be022cefd565820',
  sourceMap: null,
  lazy: false,
  bare: true,
  mainModule: false,
  imported: true,
  installPath: 'zodiase-mdl.json' }
{ type: 'js',
  data: <Buffer 2f 2f 20 54 68 65 73 65 20 73 74 79 6c 65 73 20 68 61 76 65 20 61 6c 72 65 61 64 79 20 62 65 65 6e 20 61 70 70 6c 69 65 64 20 74 6f 20 74 68 65 20 64 6f ...>,
  sourcePath: 'zodiase-mdl.json',
  servePath: '/client/lib/dist/material.blue-pink.min.css',
  hash: 'bf5916be0fd88667452ec454871f4856bca634d3',
  sourceMap: undefined,
  lazy: true,
  bare: true,
  mainModule: false,
  imported: false,
  installPath: 'zodiase-mdl.json' }

    at checkProperty (C:\tools\isobuild\import-scanner.js:198:15)
    at ImportScanner._combineFiles (C:\tools\isobuild\import-scanner.js:187:35)
    at C:\tools\isobuild\import-scanner.js:177:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.js:148:11)
    at C:\tools\isobuild\compiler-plugin.js:825:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:796:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:899:8)
    at C:\tools\isobuild\bundler.js:670:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:661:18)
    at C:\tools\isobuild\bundler.js:2460:14
    at C:\tools\isobuild\bundler.js:2549:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Philip\AppData\Local\.meteor\packages\meteor-tool\1.3.2-rc.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2548:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2441:31)
    at C:\tools\runners\run-app.js:591:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:581:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12
```

**Comment by Zodiase** [comment]
@ramijarrar Yeah, both 1.3 and 1.3.1.
@seifip Now that's new... The error doesn't even make sense to me... The package needs to load several different files based on the settings.

**Comment by Zodiase** [comment]
@seifip BTW how did you get that error? Were you starting the app? Also you are using Windows?

**Comment by Zodiase** [comment]
@ramijarrar Also if I remember correctly there was no issue when 1.3 was just released. That means the issue is caused by one of the core packages updated since then. ~~Possibly `"promise"`.~~ (Tested with `promise@0.5.1` and the error remains.) ~~My second guess is `templating`.~~ (Nope)

**Comment by Zodiase** [comment]
Error went away in release `1.3.2-rc.5`. ლ(ಠ_ಠლ)

**Comment by seifip** [comment]
I'm still getting

```
C:\Users\Philip\AppData\Local\.meteor\packages\coffeescript\1.0.17-rc.5\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  data: <Buffer 4d 44 6c 2e 73 65 74 74 69 6e 67 73 20 3d 20 4a 53 4f 4e 2e 70 61 72 73 65 28 64 65 63 6f 64 65 55 52 49 28 22 25 37 42 25 32 32 6a 73 4c 69 62 25 32 32 ...>,
  sourcePath: 'zodiase-mdl.json',
  servePath: '/client/lib/settings-file-checked.generated.js',
  hash: '7e71019794e668497fc7ce157be022cefd565820',
  sourceMap: null,
  lazy: false,
  bare: true,
  mainModule: false,
  imported: true,
  installPath: 'zodiase-mdl.json' }
{ type: 'js',
  data: <Buffer 2f 2f 20 54 68 65 73 65 20 73 74 79 6c 65 73 20 68 61 76 65 20 61 6c 72 65 61 64 79 20 62 65 65 6e 20 61 70 70 6c 69 65 64 20 74 6f 20 74 68 65 20 64 6f ...>,
  sourcePath: 'zodiase-mdl.json',
  servePath: '/client/lib/dist/material.blue-pink.min.css',
  hash: 'bf5916be0fd88667452ec454871f4856bca634d3',
  sourceMap: undefined,
  lazy: true,
  bare: true,
  mainModule: false,
  imported: false,
  installPath: 'zodiase-mdl.json' }

    at checkProperty (C:\tools\isobuild\import-scanner.js:198:15)
    at ImportScanner._combineFiles (C:\tools\isobuild\import-scanner.js:187:35)
    at C:\tools\isobuild\import-scanner.js:177:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.js:148:11)
    at C:\tools\isobuild\compiler-plugin.js:825:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:796:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:913:8)
    at C:\tools\isobuild\bundler.js:684:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:675:18)
    at C:\tools\isobuild\bundler.js:2474:14
    at C:\tools\isobuild\bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Philip\AppData\Local\.meteor\packages\meteor-tool\1.3.2-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2562:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2455:31)
    at C:\tools\runners\run-app.js:591:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:581:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12
```

on Windows with rc5.

**Comment by Zodiase** [comment]
@seifip I'm not getting this error. This whole thing looks to me is all about issues within Meteor 1.3.x, and unfortunately I don't have the time to dig out the cause for MDG. I found a similar issue on Meteor's repo that you could join: meteor/meteor#6806.

**Comment by Zodiase** [comment]
This particular issue seems to be fixed at some point. Could not reproduce it in 1.3.1 now.
